// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/listings/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/api/conversations": {
    params: {};
  };
  "/api/messages/:id": {
    params: {
      "id": string;
    };
  };
  "/listings": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile/agency": {
    params: {};
  };
  "/profile/runner": {
    params: {};
  };
  "/api/translate": {
    params: {};
  };
  "/listings/:id": {
    params: {
      "id": string;
    };
  };
  "/listings/:id/backup": {
    params: {
      "id": string;
    };
  };
  "/listings/new": {
    params: {};
  };
  "/my-listings": {
    params: {};
  };
  "/api/unread": {
    params: {};
  };
  "/api/saved": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/messages": {
    params: {};
  };
  "/messages/:id": {
    params: {
      "id": string;
    };
  };
  "/register": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/report": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/saved": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/listings/:id/edit" | "/api/conversations" | "/api/messages/:id" | "/listings" | "/profile" | "/profile/agency" | "/profile/runner" | "/api/translate" | "/listings/:id" | "/listings/:id/backup" | "/listings/new" | "/my-listings" | "/api/unread" | "/api/saved" | "/dashboard" | "/messages" | "/messages/:id" | "/register" | "/settings" | "/contact" | "/logout" | "/report" | "/login" | "/saved";
  };
  "routes/listings.$id_.edit.tsx": {
    id: "routes/listings.$id_.edit";
    page: "/listings/:id/edit";
  };
  "routes/api.conversations.tsx": {
    id: "routes/api.conversations";
    page: "/api/conversations";
  };
  "routes/api.messages.$id.tsx": {
    id: "routes/api.messages.$id";
    page: "/api/messages/:id";
  };
  "routes/listings._index.tsx": {
    id: "routes/listings._index";
    page: "/listings";
  };
  "routes/profile._index.tsx": {
    id: "routes/profile._index";
    page: "/profile";
  };
  "routes/profile.agency.tsx": {
    id: "routes/profile.agency";
    page: "/profile/agency";
  };
  "routes/profile.runner.tsx": {
    id: "routes/profile.runner";
    page: "/profile/runner";
  };
  "routes/api.translate.tsx": {
    id: "routes/api.translate";
    page: "/api/translate";
  };
  "routes/listings.$id.tsx": {
    id: "routes/listings.$id";
    page: "/listings/:id" | "/listings/:id/backup";
  };
  "routes/listings.$id.backup.tsx": {
    id: "routes/listings.$id.backup";
    page: "/listings/:id/backup";
  };
  "routes/listings.new.tsx": {
    id: "routes/listings.new";
    page: "/listings/new";
  };
  "routes/my-listings.tsx": {
    id: "routes/my-listings";
    page: "/my-listings";
  };
  "routes/api.unread.tsx": {
    id: "routes/api.unread";
    page: "/api/unread";
  };
  "routes/api.saved.tsx": {
    id: "routes/api.saved";
    page: "/api/saved";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/messages.tsx": {
    id: "routes/messages";
    page: "/messages" | "/messages/:id";
  };
  "routes/messages._index.tsx": {
    id: "routes/messages._index";
    page: "/messages";
  };
  "routes/messages.$id.tsx": {
    id: "routes/messages.$id";
    page: "/messages/:id";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/report.tsx": {
    id: "routes/report";
    page: "/report";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/saved.tsx": {
    id: "routes/saved";
    page: "/saved";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/listings.$id_.edit": typeof import("./app/routes/listings.$id_.edit.tsx");
  "routes/api.conversations": typeof import("./app/routes/api.conversations.tsx");
  "routes/api.messages.$id": typeof import("./app/routes/api.messages.$id.tsx");
  "routes/listings._index": typeof import("./app/routes/listings._index.tsx");
  "routes/profile._index": typeof import("./app/routes/profile._index.tsx");
  "routes/profile.agency": typeof import("./app/routes/profile.agency.tsx");
  "routes/profile.runner": typeof import("./app/routes/profile.runner.tsx");
  "routes/api.translate": typeof import("./app/routes/api.translate.tsx");
  "routes/listings.$id": typeof import("./app/routes/listings.$id.tsx");
  "routes/listings.$id.backup": typeof import("./app/routes/listings.$id.backup.tsx");
  "routes/listings.new": typeof import("./app/routes/listings.new.tsx");
  "routes/my-listings": typeof import("./app/routes/my-listings.tsx");
  "routes/api.unread": typeof import("./app/routes/api.unread.tsx");
  "routes/api.saved": typeof import("./app/routes/api.saved.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/messages": typeof import("./app/routes/messages.tsx");
  "routes/messages._index": typeof import("./app/routes/messages._index.tsx");
  "routes/messages.$id": typeof import("./app/routes/messages.$id.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/report": typeof import("./app/routes/report.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/saved": typeof import("./app/routes/saved.tsx");
};