import { sendTemplatedEmail } from "../app/lib/email/service.server";
import type { EmailLocale } from "../app/lib/email/types";

type CliOptions = {
  to: string;
  locale: EmailLocale;
};

function parseArgs(argv: string[]): CliOptions {
  const options: CliOptions = {
    to: "support@runoot.com",
    locale: "en",
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--to" && argv[i + 1]) {
      options.to = argv[i + 1];
      i += 1;
      continue;
    }
    if (arg === "--locale" && argv[i + 1]) {
      const rawLocale = String(argv[i + 1]).toLowerCase();
      if (["en", "it", "de", "fr", "es", "nl", "pt"].includes(rawLocale)) {
        options.locale = rawLocale as EmailLocale;
      }
      i += 1;
    }
  }

  return options;
}

async function main() {
  const { to, locale } = parseArgs(process.argv.slice(2));
  const baseUrl = (process.env.APP_URL || "http://localhost:5173").replace(/\/$/, "");

  const tests: Array<{ name: string; run: () => ReturnType<typeof sendTemplatedEmail> }> = [
    {
      name: "account_setup",
      run: () =>
        sendTemplatedEmail({
          to,
          locale,
          templateId: "account_setup",
          payload: {
            setupLink: `${baseUrl}/reset-password?token=test-account-setup`,
          },
        }),
    },
    {
      name: "password_reset",
      run: () =>
        sendTemplatedEmail({
          to,
          locale,
          templateId: "password_reset",
          payload: {
            resetLink: `${baseUrl}/reset-password?token=test-password-reset`,
          },
        }),
    },
    {
      name: "platform_notification",
      run: () =>
        sendTemplatedEmail({
          to,
          locale,
          templateId: "platform_notification",
          payload: {
            title: "Runoot Test Notification",
            message: "This is a test notification email generated by scripts/send-email-previews.ts.",
            ctaLabel: "Open Runoot",
            ctaUrl: `${baseUrl}/login`,
          },
        }),
    },
    {
      name: "referral_invite",
      run: () =>
        sendTemplatedEmail({
          to,
          locale,
          templateId: "referral_invite",
          payload: {
            inviterName: "Marco Team Leader",
            referralLink: `${baseUrl}/join/ABC123`,
            welcomeMessage: "Happy to have you with us.",
          },
        }),
    },
    {
      name: "team_referral_invite",
      run: () =>
        sendTemplatedEmail({
          to,
          locale,
          templateId: "team_referral_invite",
          payload: {
            inviterName: "Giulia Team Leader",
            acceptLink: `${baseUrl}/join-team/test-invite-id`,
            personalMessage: "Join my Runoot team and let's coordinate upcoming races.",
          },
        }),
    },
  ];

  console.log(`Sending ${tests.length} email previews to ${to} (locale: ${locale})...`);

  let sent = 0;
  let failed = 0;
  const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

  async function runWithRetry(
    runner: () => ReturnType<typeof sendTemplatedEmail>,
    maxAttempts = 3
  ): Promise<Awaited<ReturnType<typeof sendTemplatedEmail>>> {
    for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
      const result = await runner();
      const isRateLimited = !result.ok && (result.error || "").includes("429");
      if (!isRateLimited || attempt === maxAttempts) return result;
      await sleep(1000 * attempt);
    }
    return { ok: false, error: "Unknown retry failure" };
  }

  for (const test of tests) {
    const result = await runWithRetry(test.run);
    if (result.ok) {
      sent += 1;
      console.log(`OK   ${test.name}${result.providerId ? ` (${result.providerId})` : ""}`);
    } else {
      failed += 1;
      console.error(`FAIL ${test.name}: ${result.error || "unknown error"}`);
    }
    // Keep well under 2 req/sec to avoid provider rate-limit.
    await sleep(700);
  }

  console.log(`Done. Sent: ${sent}, Failed: ${failed}`);
  if (failed > 0) process.exitCode = 1;
}

main().catch((error) => {
  console.error("email preview script failed:", error);
  process.exit(1);
});
